=head1 NAME

DBIx::DBO2::ToDo - Tasks, ideas, and bug reports

=head1 TODO

=over 4

=item *

It seems to be better practice to query for test DSN in Makefile.PL, rather than in test.pl.


=item *

The current test script is woefully inadqueate, and does not test the full public interface of this framework.
 

=item *

Records should be using prototypes for new(), to simplify both setting defaults and changing the default implementation class.


=item *

Continue to add field types, while trying to maintain some degree of consistency in naming and clarity in interface.


=item *

Move most of the primary key logic into primary_key field declarations, including fetch_id.


=item *

Add automatic generation of useful indexes.


=item *

Finish building out field auto-detection to include on-demand method generation.


=item *

Fix RecordSet filtering and sorting.


=item *

Replace Record::DefinedRow with Table::Static.


=item *

Former versions of this package used the DBO::* namespace, but this is a poor choice for public redistribution, ie CPAN. But what would be a better name for this framework? Some candidates:

  DBIx::DBO2
  DBIx::ORM


=item *

Move all of the AUTHORS and LICENSE blocks to ReadMe.pod
Include a SEE ALSO in all modules pointing to ReadMe.pod.


=back


=head1 SEE ALSO

L<DBIx::DBO2::ReadMe>

=cut
